### ISSUE TITLE
For English Language

### ISSUE THREAD

**Issue by IDKYamHere** [kuchynkm/real-time-japanese-OCR#1]
I'm curious to know how to make this project run for English characters.

**Comment by kuchynkm** [comment]
That should be no problem, actually. It can be done in just two steps: 

1) retrain the model for latin alphabet 
2) replace `ind_to_char` (dictionary of hiragana labels) in `recognition.py` with a dictionary of letters

The first step requires a bit of effort, but there is plenty of dataset with handwritten/printed letters available for training the model. Moreover, one can use Jupyter notebook I made when I was training this hiragana model. It's available in my other repository [here](https://github.com/kuchynkm/hiragana-recognition-cnn).

**Comment by IDKYamHere** [comment]
Thanks a lot! Will give it a try. If I make any progress will create a new pull request.
Closing this issue.
